### ISSUE TITLE
Merge com http://doadordecodigo.com.br/

### ISSUE THREAD

**Issue by lucianosousa** [socialpullrequest/socialpullrequest.github.io#13]
Eu tentei por algum tempo tocar o Doador de Código[1], mas sozinho complicou bastante

Eu tenho algumas idéias de como atrair developers e como também capturar projetos a serem ajudados.

Tenho interesse de migrar tudo meu para cá, vocês tem algum interesse?

[1] http://doadordecodigo.com.br/

**Comment by victorlcampos** [comment]
@raphamorim e @jonatasemidio

**Comment by jonatasemidio** [comment]
Fala @lucianosousa, fico feliz por ver o quanto você quer contribuir ... É desse tipo de vibe que a comunidade precisa.

A idéia do #SPR é envolver a comunidade na evolução dos projetos, tanto em código qunato em idéias.

Nesse primeiro momento, estamos criando a estrutura inicial, só para não chegarmos sem nada no primeiro dia que apresentarmos a idéia para a comunidade.

Marcaremos encontros frequentes, tanto para atender os projetos sociais, quando para evoluir a própria ferramenta para melhor atender as necessidades existentes. A sua ideia será muito bem vinda nos encontros que virão.

**Comment by lucianosousa** [comment]
@jonatasemidio quando rolar o próximo evento por favor me avisa. ;)

**Comment by jonatasemidio** [comment]
Opa pode deixar @lucianosousa !! Se possível já deixa o seu cadastro no site como DEV
