### ISSUE TITLE
Modificar layout para atender o novo Logo(marca).

### ISSUE THREAD

**Issue by victorlcampos** [socialpullrequest/socialpullrequest.github.io#2]
A logomarca(e cores) do socialpullrequest foram definidas na issue:

https://github.com/socialpullrequest/socialpullrequest/issues/4#issuecomment-176440945

Mudar o layout.

**Comment by afonsopacifer** [comment]
hoje a tarde eu mando um PR com as modificações :)

**Comment by jonatasemidio** [comment]
Caramba...  Que bom que vcs estão engajados...  Sou péssimo em fronte,  não
sei em que pé estaria sem essa equipe. Obrigado mesmo!

Em sáb, 30 de jan de 2016 12:52, Afonso Pacifer notifications@github.com
escreveu:
