### ISSUE TITLE
Sync Google Form

### ISSUE THREAD

**Issue by raphamorim** [socialpullrequest/socialpullrequest.github.io#8]
Ler excel gerado pelos formulários do google form e criar JSON a partir desses dados. Então o Jekyll lê o JSON gerado para dar build das páginas estáticas.

Ref: https://developers.google.com/apps-script/

**Comment by victorlcampos** [comment]
Para gerar um feed atom usando o spreadsheet basta usar a url:
https://spreadsheets.google.com/feeds/list/spreed_sheet_id/od6/public/values?alt=json

É necessário ter o formulário publicado, @jonatasemidio, pode compartilhar com a gente?

**Comment by victorlcampos** [comment]
@jonatasemidio, colocar no spreadsheet de resposta, uma coluna dizendo que está aprovado ou não.

**Comment by victorlcampos** [comment]
Plugin para consumir o jekyll-get
https://github.com/18F/jekyll-get

**Comment by jonatasemidio** [comment]
@victorlcampos com relação a publicação ele já está (vide links no site) e tanto você como o @raphamorim junto com todo o time do SPR está com acesso ... O que realmente está acontecendo?

Já com relação a coluna, criei a coluna Status e os status (Aprovado, Analise, Reprovado)...
Era mais ou menos isso?
